version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fraudshield-backend
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001,http://frontend:3000
      - DEBUG=False
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - frontend
    networks:
      - fraudshield-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fraudshield-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000/api/v1
    volumes:
      - ./frontend:/app
    command: npm run dev
    networks:
      - fraudshield-network

networks:
  fraudshield-network:
    driver: bridge
